// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(GorpFFIFFI)
import GorpFFIFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_gorp_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_gorp_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureGorpFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * FFI-safe wrapper around AgentHandle
 */
public protocol FfiAgentHandleProtocol: AnyObject, Sendable {
    
    /**
     * Abandon a session that was created but never used
     */
    func abandonSession(sessionId: String) 
    
    /**
     * Cancel an in-progress prompt
     */
    func cancel(sessionId: String) throws 
    
    /**
     * Load an existing session by ID
     */
    func loadSession(sessionId: String) throws 
    
    /**
     * Get the backend name
     */
    func name()  -> String
    
    /**
     * Create a new session, returns session ID
     */
    func newSession() throws  -> String
    
    /**
     * Send a prompt with streaming callback
     *
     * Returns immediately. Events are delivered via callback on background thread.
     */
    func prompt(sessionId: String, text: String, callback: AgentEventCallback) throws 
    
}
/**
 * FFI-safe wrapper around AgentHandle
 */
open class FfiAgentHandle: FfiAgentHandleProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_gorp_ffi_fn_clone_ffiagenthandle(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        try! rustCall { uniffi_gorp_ffi_fn_free_ffiagenthandle(handle, $0) }
    }

    

    
    /**
     * Abandon a session that was created but never used
     */
open func abandonSession(sessionId: String)  {try! rustCall() {
    uniffi_gorp_ffi_fn_method_ffiagenthandle_abandon_session(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(sessionId),$0
    )
}
}
    
    /**
     * Cancel an in-progress prompt
     */
open func cancel(sessionId: String)throws   {try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_gorp_ffi_fn_method_ffiagenthandle_cancel(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(sessionId),$0
    )
}
}
    
    /**
     * Load an existing session by ID
     */
open func loadSession(sessionId: String)throws   {try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_gorp_ffi_fn_method_ffiagenthandle_load_session(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(sessionId),$0
    )
}
}
    
    /**
     * Get the backend name
     */
open func name() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_gorp_ffi_fn_method_ffiagenthandle_name(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Create a new session, returns session ID
     */
open func newSession()throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_gorp_ffi_fn_method_ffiagenthandle_new_session(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Send a prompt with streaming callback
     *
     * Returns immediately. Events are delivered via callback on background thread.
     */
open func prompt(sessionId: String, text: String, callback: AgentEventCallback)throws   {try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_gorp_ffi_fn_method_ffiagenthandle_prompt(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(sessionId),
        FfiConverterString.lower(text),
        FfiConverterCallbackInterfaceAgentEventCallback_lower(callback),$0
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiAgentHandle: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = FfiAgentHandle

    public static func lift(_ handle: UInt64) throws -> FfiAgentHandle {
        return FfiAgentHandle(unsafeFromHandle: handle)
    }

    public static func lower(_ value: FfiAgentHandle) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiAgentHandle {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: FfiAgentHandle, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiAgentHandle_lift(_ handle: UInt64) throws -> FfiAgentHandle {
    return try FfiConverterTypeFfiAgentHandle.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiAgentHandle_lower(_ value: FfiAgentHandle) -> UInt64 {
    return FfiConverterTypeFfiAgentHandle.lower(value)
}






/**
 * FFI-safe wrapper around AgentRegistry
 */
public protocol FfiAgentRegistryProtocol: AnyObject, Sendable {
    
    /**
     * List available backend names
     */
    func availableBackends()  -> [String]
    
    /**
     * Create a backend by name with JSON configuration
     */
    func create(name: String, configJson: String) throws  -> FfiAgentHandle
    
}
/**
 * FFI-safe wrapper around AgentRegistry
 */
open class FfiAgentRegistry: FfiAgentRegistryProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_gorp_ffi_fn_clone_ffiagentregistry(self.handle, $0) }
    }
    /**
     * Create a new registry with all available backends
     */
public convenience init() {
    let handle =
        try! rustCall() {
    uniffi_gorp_ffi_fn_constructor_ffiagentregistry_new($0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        try! rustCall { uniffi_gorp_ffi_fn_free_ffiagentregistry(handle, $0) }
    }

    

    
    /**
     * List available backend names
     */
open func availableBackends() -> [String]  {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
    uniffi_gorp_ffi_fn_method_ffiagentregistry_available_backends(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Create a backend by name with JSON configuration
     */
open func create(name: String, configJson: String)throws  -> FfiAgentHandle  {
    return try  FfiConverterTypeFfiAgentHandle_lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_gorp_ffi_fn_method_ffiagentregistry_create(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(name),
        FfiConverterString.lower(configJson),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiAgentRegistry: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = FfiAgentRegistry

    public static func lift(_ handle: UInt64) throws -> FfiAgentRegistry {
        return FfiAgentRegistry(unsafeFromHandle: handle)
    }

    public static func lower(_ value: FfiAgentRegistry) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiAgentRegistry {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: FfiAgentRegistry, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiAgentRegistry_lift(_ handle: UInt64) throws -> FfiAgentRegistry {
    return try FfiConverterTypeFfiAgentRegistry.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiAgentRegistry_lower(_ value: FfiAgentRegistry) -> UInt64 {
    return FfiConverterTypeFfiAgentRegistry.lower(value)
}






/**
 * FFI wrapper for SchedulerStore
 */
public protocol FfiSchedulerStoreProtocol: AnyObject, Sendable {
    
    /**
     * Cancel a schedule
     */
    func cancelSchedule(id: String) throws  -> Bool
    
    /**
     * Create a new scheduled prompt
     *
     * Time expression can be:
     * - Cron expression: "0 9 * * *" (daily at 9am)
     * - Relative time: "in 5 minutes", "in 2 hours"
     * - Absolute time: "at 3pm", "at 14:30"
     */
    func createSchedule(channelName: String, roomId: String, prompt: String, createdBy: String, timeExpression: String, timezone: String) throws  -> FfiScheduledPrompt
    
    /**
     * Delete a schedule by ID
     */
    func deleteSchedule(id: String) throws  -> Bool
    
    /**
     * Get a schedule by ID
     */
    func getById(id: String) throws  -> FfiScheduledPrompt?
    
    /**
     * List all scheduled prompts
     */
    func listAll() throws  -> [FfiScheduledPrompt]
    
    /**
     * List schedules for a specific channel
     */
    func listByChannel(channelName: String) throws  -> [FfiScheduledPrompt]
    
    /**
     * List schedules for a specific room
     */
    func listByRoom(roomId: String) throws  -> [FfiScheduledPrompt]
    
    /**
     * Pause a schedule
     */
    func pauseSchedule(id: String) throws  -> Bool
    
    /**
     * Resume a paused schedule
     */
    func resumeSchedule(id: String) throws  -> Bool
    
}
/**
 * FFI wrapper for SchedulerStore
 */
open class FfiSchedulerStore: FfiSchedulerStoreProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_gorp_ffi_fn_clone_ffischedulerstore(self.handle, $0) }
    }
    /**
     * Create a scheduler store that shares the session store's database
     */
public convenience init(sessionStore: FfiSessionStore)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_gorp_ffi_fn_constructor_ffischedulerstore_new(
        FfiConverterTypeFfiSessionStore_lower(sessionStore),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        try! rustCall { uniffi_gorp_ffi_fn_free_ffischedulerstore(handle, $0) }
    }

    

    
    /**
     * Cancel a schedule
     */
open func cancelSchedule(id: String)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_gorp_ffi_fn_method_ffischedulerstore_cancel_schedule(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),$0
    )
})
}
    
    /**
     * Create a new scheduled prompt
     *
     * Time expression can be:
     * - Cron expression: "0 9 * * *" (daily at 9am)
     * - Relative time: "in 5 minutes", "in 2 hours"
     * - Absolute time: "at 3pm", "at 14:30"
     */
open func createSchedule(channelName: String, roomId: String, prompt: String, createdBy: String, timeExpression: String, timezone: String)throws  -> FfiScheduledPrompt  {
    return try  FfiConverterTypeFfiScheduledPrompt_lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_gorp_ffi_fn_method_ffischedulerstore_create_schedule(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(channelName),
        FfiConverterString.lower(roomId),
        FfiConverterString.lower(prompt),
        FfiConverterString.lower(createdBy),
        FfiConverterString.lower(timeExpression),
        FfiConverterString.lower(timezone),$0
    )
})
}
    
    /**
     * Delete a schedule by ID
     */
open func deleteSchedule(id: String)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_gorp_ffi_fn_method_ffischedulerstore_delete_schedule(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),$0
    )
})
}
    
    /**
     * Get a schedule by ID
     */
open func getById(id: String)throws  -> FfiScheduledPrompt?  {
    return try  FfiConverterOptionTypeFfiScheduledPrompt.lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_gorp_ffi_fn_method_ffischedulerstore_get_by_id(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),$0
    )
})
}
    
    /**
     * List all scheduled prompts
     */
open func listAll()throws  -> [FfiScheduledPrompt]  {
    return try  FfiConverterSequenceTypeFfiScheduledPrompt.lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_gorp_ffi_fn_method_ffischedulerstore_list_all(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * List schedules for a specific channel
     */
open func listByChannel(channelName: String)throws  -> [FfiScheduledPrompt]  {
    return try  FfiConverterSequenceTypeFfiScheduledPrompt.lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_gorp_ffi_fn_method_ffischedulerstore_list_by_channel(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(channelName),$0
    )
})
}
    
    /**
     * List schedules for a specific room
     */
open func listByRoom(roomId: String)throws  -> [FfiScheduledPrompt]  {
    return try  FfiConverterSequenceTypeFfiScheduledPrompt.lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_gorp_ffi_fn_method_ffischedulerstore_list_by_room(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(roomId),$0
    )
})
}
    
    /**
     * Pause a schedule
     */
open func pauseSchedule(id: String)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_gorp_ffi_fn_method_ffischedulerstore_pause_schedule(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),$0
    )
})
}
    
    /**
     * Resume a paused schedule
     */
open func resumeSchedule(id: String)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_gorp_ffi_fn_method_ffischedulerstore_resume_schedule(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiSchedulerStore: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = FfiSchedulerStore

    public static func lift(_ handle: UInt64) throws -> FfiSchedulerStore {
        return FfiSchedulerStore(unsafeFromHandle: handle)
    }

    public static func lower(_ value: FfiSchedulerStore) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiSchedulerStore {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: FfiSchedulerStore, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSchedulerStore_lift(_ handle: UInt64) throws -> FfiSchedulerStore {
    return try FfiConverterTypeFfiSchedulerStore.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSchedulerStore_lower(_ value: FfiSchedulerStore) -> UInt64 {
    return FfiConverterTypeFfiSchedulerStore.lower(value)
}






/**
 * FFI wrapper for SessionStore
 */
public protocol FfiSessionStoreProtocol: AnyObject, Sendable {
    
    /**
     * Create a new channel
     */
    func createChannel(channelName: String, roomId: String) throws  -> FfiChannel
    
    /**
     * Delete a channel by room ID
     */
    func deleteByRoom(roomId: String) throws  -> String?
    
    /**
     * Delete a channel by name
     */
    func deleteChannel(channelName: String) throws 
    
    /**
     * Get channel by name
     */
    func getByName(channelName: String) throws  -> FfiChannel?
    
    /**
     * Get channel by room ID
     */
    func getByRoom(roomId: String) throws  -> FfiChannel?
    
    /**
     * Get channel by session ID
     */
    func getBySessionId(sessionId: String) throws  -> FfiChannel?
    
    /**
     * Get a setting value
     */
    func getSetting(key: String) throws  -> String?
    
    /**
     * List all channels
     */
    func listAll() throws  -> [FfiChannel]
    
    /**
     * Mark a channel as started
     */
    func markStarted(roomId: String) throws 
    
    /**
     * Reset a channel's session
     */
    func resetSession(channelName: String, newSessionId: String) throws 
    
    /**
     * Set a setting value
     */
    func setSetting(key: String, value: String) throws 
    
    /**
     * Update backend type for a channel
     */
    func updateBackendType(channelName: String, backendType: String?) throws 
    
}
/**
 * FFI wrapper for SessionStore
 */
open class FfiSessionStore: FfiSessionStoreProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_gorp_ffi_fn_clone_ffisessionstore(self.handle, $0) }
    }
    /**
     * Create/open a session store at the given workspace path
     */
public convenience init(workspacePath: String)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_gorp_ffi_fn_constructor_ffisessionstore_new(
        FfiConverterString.lower(workspacePath),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        try! rustCall { uniffi_gorp_ffi_fn_free_ffisessionstore(handle, $0) }
    }

    

    
    /**
     * Create a new channel
     */
open func createChannel(channelName: String, roomId: String)throws  -> FfiChannel  {
    return try  FfiConverterTypeFfiChannel_lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_gorp_ffi_fn_method_ffisessionstore_create_channel(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(channelName),
        FfiConverterString.lower(roomId),$0
    )
})
}
    
    /**
     * Delete a channel by room ID
     */
open func deleteByRoom(roomId: String)throws  -> String?  {
    return try  FfiConverterOptionString.lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_gorp_ffi_fn_method_ffisessionstore_delete_by_room(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(roomId),$0
    )
})
}
    
    /**
     * Delete a channel by name
     */
open func deleteChannel(channelName: String)throws   {try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_gorp_ffi_fn_method_ffisessionstore_delete_channel(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(channelName),$0
    )
}
}
    
    /**
     * Get channel by name
     */
open func getByName(channelName: String)throws  -> FfiChannel?  {
    return try  FfiConverterOptionTypeFfiChannel.lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_gorp_ffi_fn_method_ffisessionstore_get_by_name(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(channelName),$0
    )
})
}
    
    /**
     * Get channel by room ID
     */
open func getByRoom(roomId: String)throws  -> FfiChannel?  {
    return try  FfiConverterOptionTypeFfiChannel.lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_gorp_ffi_fn_method_ffisessionstore_get_by_room(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(roomId),$0
    )
})
}
    
    /**
     * Get channel by session ID
     */
open func getBySessionId(sessionId: String)throws  -> FfiChannel?  {
    return try  FfiConverterOptionTypeFfiChannel.lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_gorp_ffi_fn_method_ffisessionstore_get_by_session_id(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(sessionId),$0
    )
})
}
    
    /**
     * Get a setting value
     */
open func getSetting(key: String)throws  -> String?  {
    return try  FfiConverterOptionString.lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_gorp_ffi_fn_method_ffisessionstore_get_setting(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(key),$0
    )
})
}
    
    /**
     * List all channels
     */
open func listAll()throws  -> [FfiChannel]  {
    return try  FfiConverterSequenceTypeFfiChannel.lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_gorp_ffi_fn_method_ffisessionstore_list_all(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Mark a channel as started
     */
open func markStarted(roomId: String)throws   {try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_gorp_ffi_fn_method_ffisessionstore_mark_started(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(roomId),$0
    )
}
}
    
    /**
     * Reset a channel's session
     */
open func resetSession(channelName: String, newSessionId: String)throws   {try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_gorp_ffi_fn_method_ffisessionstore_reset_session(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(channelName),
        FfiConverterString.lower(newSessionId),$0
    )
}
}
    
    /**
     * Set a setting value
     */
open func setSetting(key: String, value: String)throws   {try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_gorp_ffi_fn_method_ffisessionstore_set_setting(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(key),
        FfiConverterString.lower(value),$0
    )
}
}
    
    /**
     * Update backend type for a channel
     */
open func updateBackendType(channelName: String, backendType: String?)throws   {try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_gorp_ffi_fn_method_ffisessionstore_update_backend_type(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(channelName),
        FfiConverterOptionString.lower(backendType),$0
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiSessionStore: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = FfiSessionStore

    public static func lift(_ handle: UInt64) throws -> FfiSessionStore {
        return FfiSessionStore(unsafeFromHandle: handle)
    }

    public static func lower(_ value: FfiSessionStore) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiSessionStore {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: FfiSessionStore, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSessionStore_lift(_ handle: UInt64) throws -> FfiSessionStore {
    return try FfiConverterTypeFfiSessionStore.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSessionStore_lower(_ value: FfiSessionStore) -> UInt64 {
    return FfiConverterTypeFfiSessionStore.lower(value)
}




/**
 * FFI-safe channel record
 */
public struct FfiChannel: Equatable, Hashable {
    public let channelName: String
    public let roomId: String
    public let sessionId: String
    public let directory: String
    public let started: Bool
    public let createdAt: String
    public let backendType: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(channelName: String, roomId: String, sessionId: String, directory: String, started: Bool, createdAt: String, backendType: String?) {
        self.channelName = channelName
        self.roomId = roomId
        self.sessionId = sessionId
        self.directory = directory
        self.started = started
        self.createdAt = createdAt
        self.backendType = backendType
    }

    
}

#if compiler(>=6)
extension FfiChannel: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiChannel: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiChannel {
        return
            try FfiChannel(
                channelName: FfiConverterString.read(from: &buf), 
                roomId: FfiConverterString.read(from: &buf), 
                sessionId: FfiConverterString.read(from: &buf), 
                directory: FfiConverterString.read(from: &buf), 
                started: FfiConverterBool.read(from: &buf), 
                createdAt: FfiConverterString.read(from: &buf), 
                backendType: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiChannel, into buf: inout [UInt8]) {
        FfiConverterString.write(value.channelName, into: &buf)
        FfiConverterString.write(value.roomId, into: &buf)
        FfiConverterString.write(value.sessionId, into: &buf)
        FfiConverterString.write(value.directory, into: &buf)
        FfiConverterBool.write(value.started, into: &buf)
        FfiConverterString.write(value.createdAt, into: &buf)
        FfiConverterOptionString.write(value.backendType, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiChannel_lift(_ buf: RustBuffer) throws -> FfiChannel {
    return try FfiConverterTypeFfiChannel.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiChannel_lower(_ value: FfiChannel) -> RustBuffer {
    return FfiConverterTypeFfiChannel.lower(value)
}


/**
 * FFI-safe scheduled prompt record
 */
public struct FfiScheduledPrompt: Equatable, Hashable {
    public let id: String
    public let channelName: String
    public let roomId: String
    public let prompt: String
    public let createdBy: String
    public let createdAt: String
    public let executeAt: String?
    public let cronExpression: String?
    public let lastExecutedAt: String?
    public let nextExecutionAt: String
    public let status: FfiScheduleStatus
    public let errorMessage: String?
    public let executionCount: Int32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, channelName: String, roomId: String, prompt: String, createdBy: String, createdAt: String, executeAt: String?, cronExpression: String?, lastExecutedAt: String?, nextExecutionAt: String, status: FfiScheduleStatus, errorMessage: String?, executionCount: Int32) {
        self.id = id
        self.channelName = channelName
        self.roomId = roomId
        self.prompt = prompt
        self.createdBy = createdBy
        self.createdAt = createdAt
        self.executeAt = executeAt
        self.cronExpression = cronExpression
        self.lastExecutedAt = lastExecutedAt
        self.nextExecutionAt = nextExecutionAt
        self.status = status
        self.errorMessage = errorMessage
        self.executionCount = executionCount
    }

    
}

#if compiler(>=6)
extension FfiScheduledPrompt: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiScheduledPrompt: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiScheduledPrompt {
        return
            try FfiScheduledPrompt(
                id: FfiConverterString.read(from: &buf), 
                channelName: FfiConverterString.read(from: &buf), 
                roomId: FfiConverterString.read(from: &buf), 
                prompt: FfiConverterString.read(from: &buf), 
                createdBy: FfiConverterString.read(from: &buf), 
                createdAt: FfiConverterString.read(from: &buf), 
                executeAt: FfiConverterOptionString.read(from: &buf), 
                cronExpression: FfiConverterOptionString.read(from: &buf), 
                lastExecutedAt: FfiConverterOptionString.read(from: &buf), 
                nextExecutionAt: FfiConverterString.read(from: &buf), 
                status: FfiConverterTypeFfiScheduleStatus.read(from: &buf), 
                errorMessage: FfiConverterOptionString.read(from: &buf), 
                executionCount: FfiConverterInt32.read(from: &buf)
        )
    }

    public static func write(_ value: FfiScheduledPrompt, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.channelName, into: &buf)
        FfiConverterString.write(value.roomId, into: &buf)
        FfiConverterString.write(value.prompt, into: &buf)
        FfiConverterString.write(value.createdBy, into: &buf)
        FfiConverterString.write(value.createdAt, into: &buf)
        FfiConverterOptionString.write(value.executeAt, into: &buf)
        FfiConverterOptionString.write(value.cronExpression, into: &buf)
        FfiConverterOptionString.write(value.lastExecutedAt, into: &buf)
        FfiConverterString.write(value.nextExecutionAt, into: &buf)
        FfiConverterTypeFfiScheduleStatus.write(value.status, into: &buf)
        FfiConverterOptionString.write(value.errorMessage, into: &buf)
        FfiConverterInt32.write(value.executionCount, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiScheduledPrompt_lift(_ buf: RustBuffer) throws -> FfiScheduledPrompt {
    return try FfiConverterTypeFfiScheduledPrompt.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiScheduledPrompt_lower(_ value: FfiScheduledPrompt) -> RustBuffer {
    return FfiConverterTypeFfiScheduledPrompt.lower(value)
}


/**
 * FFI-safe usage statistics
 */
public struct FfiUsage: Equatable, Hashable {
    public let inputTokens: UInt64
    public let outputTokens: UInt64
    public let cacheReadTokens: UInt64?
    public let cacheWriteTokens: UInt64?
    public let costUsd: Double?
    /**
     * Backend-specific usage data as JSON string
     */
    public let extraJson: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(inputTokens: UInt64, outputTokens: UInt64, cacheReadTokens: UInt64?, cacheWriteTokens: UInt64?, costUsd: Double?, 
        /**
         * Backend-specific usage data as JSON string
         */extraJson: String?) {
        self.inputTokens = inputTokens
        self.outputTokens = outputTokens
        self.cacheReadTokens = cacheReadTokens
        self.cacheWriteTokens = cacheWriteTokens
        self.costUsd = costUsd
        self.extraJson = extraJson
    }

    
}

#if compiler(>=6)
extension FfiUsage: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiUsage: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiUsage {
        return
            try FfiUsage(
                inputTokens: FfiConverterUInt64.read(from: &buf), 
                outputTokens: FfiConverterUInt64.read(from: &buf), 
                cacheReadTokens: FfiConverterOptionUInt64.read(from: &buf), 
                cacheWriteTokens: FfiConverterOptionUInt64.read(from: &buf), 
                costUsd: FfiConverterOptionDouble.read(from: &buf), 
                extraJson: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiUsage, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.inputTokens, into: &buf)
        FfiConverterUInt64.write(value.outputTokens, into: &buf)
        FfiConverterOptionUInt64.write(value.cacheReadTokens, into: &buf)
        FfiConverterOptionUInt64.write(value.cacheWriteTokens, into: &buf)
        FfiConverterOptionDouble.write(value.costUsd, into: &buf)
        FfiConverterOptionString.write(value.extraJson, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiUsage_lift(_ buf: RustBuffer) throws -> FfiUsage {
    return try FfiConverterTypeFfiUsage.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiUsage_lower(_ value: FfiUsage) -> RustBuffer {
    return FfiConverterTypeFfiUsage.lower(value)
}


/**
 * FFI-safe error type
 */
public enum FfiError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case InvalidConfig(String
    )
    case BackendError(String
    )
    case SessionError(String
    )
    case IoError(String
    )
    case DatabaseError(String
    )
    case InvalidInput(String
    )

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension FfiError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiError: FfiConverterRustBuffer {
    typealias SwiftType = FfiError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InvalidConfig(
            try FfiConverterString.read(from: &buf)
            )
        case 2: return .BackendError(
            try FfiConverterString.read(from: &buf)
            )
        case 3: return .SessionError(
            try FfiConverterString.read(from: &buf)
            )
        case 4: return .IoError(
            try FfiConverterString.read(from: &buf)
            )
        case 5: return .DatabaseError(
            try FfiConverterString.read(from: &buf)
            )
        case 6: return .InvalidInput(
            try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .InvalidConfig(v1):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .BackendError(v1):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .SessionError(v1):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .IoError(v1):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .DatabaseError(v1):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .InvalidInput(v1):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(v1, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiError_lift(_ buf: RustBuffer) throws -> FfiError {
    return try FfiConverterTypeFfiError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiError_lower(_ value: FfiError) -> RustBuffer {
    return FfiConverterTypeFfiError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * FFI-safe error codes matching gorp-agent::ErrorCode
 */

public enum FfiErrorCode: Equatable, Hashable {
    
    case timeout
    case rateLimited
    case authFailed
    case sessionOrphaned
    case toolFailed
    case permissionDenied
    case backendError
    case unknown



}

#if compiler(>=6)
extension FfiErrorCode: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiErrorCode: FfiConverterRustBuffer {
    typealias SwiftType = FfiErrorCode

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiErrorCode {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .timeout
        
        case 2: return .rateLimited
        
        case 3: return .authFailed
        
        case 4: return .sessionOrphaned
        
        case 5: return .toolFailed
        
        case 6: return .permissionDenied
        
        case 7: return .backendError
        
        case 8: return .unknown
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiErrorCode, into buf: inout [UInt8]) {
        switch value {
        
        
        case .timeout:
            writeInt(&buf, Int32(1))
        
        
        case .rateLimited:
            writeInt(&buf, Int32(2))
        
        
        case .authFailed:
            writeInt(&buf, Int32(3))
        
        
        case .sessionOrphaned:
            writeInt(&buf, Int32(4))
        
        
        case .toolFailed:
            writeInt(&buf, Int32(5))
        
        
        case .permissionDenied:
            writeInt(&buf, Int32(6))
        
        
        case .backendError:
            writeInt(&buf, Int32(7))
        
        
        case .unknown:
            writeInt(&buf, Int32(8))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiErrorCode_lift(_ buf: RustBuffer) throws -> FfiErrorCode {
    return try FfiConverterTypeFfiErrorCode.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiErrorCode_lower(_ value: FfiErrorCode) -> RustBuffer {
    return FfiConverterTypeFfiErrorCode.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * FFI-safe schedule status
 */

public enum FfiScheduleStatus: Equatable, Hashable {
    
    case active
    case paused
    case completed
    case failed
    case executing
    case cancelled



}

#if compiler(>=6)
extension FfiScheduleStatus: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiScheduleStatus: FfiConverterRustBuffer {
    typealias SwiftType = FfiScheduleStatus

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiScheduleStatus {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .active
        
        case 2: return .paused
        
        case 3: return .completed
        
        case 4: return .failed
        
        case 5: return .executing
        
        case 6: return .cancelled
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiScheduleStatus, into buf: inout [UInt8]) {
        switch value {
        
        
        case .active:
            writeInt(&buf, Int32(1))
        
        
        case .paused:
            writeInt(&buf, Int32(2))
        
        
        case .completed:
            writeInt(&buf, Int32(3))
        
        
        case .failed:
            writeInt(&buf, Int32(4))
        
        
        case .executing:
            writeInt(&buf, Int32(5))
        
        
        case .cancelled:
            writeInt(&buf, Int32(6))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiScheduleStatus_lift(_ buf: RustBuffer) throws -> FfiScheduleStatus {
    return try FfiConverterTypeFfiScheduleStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiScheduleStatus_lower(_ value: FfiScheduleStatus) -> RustBuffer {
    return FfiConverterTypeFfiScheduleStatus.lower(value)
}





/**
 * Callback interface implemented by Swift/Kotlin
 */
public protocol AgentEventCallback: AnyObject, Sendable {
    
    func onText(text: String) 
    
    func onToolStart(id: String, name: String, inputJson: String) 
    
    func onToolProgress(id: String, updateJson: String) 
    
    func onToolEnd(id: String, name: String, outputJson: String, success: Bool, durationMs: UInt64) 
    
    func onResult(text: String, usage: FfiUsage?, metadataJson: String) 
    
    func onError(code: FfiErrorCode, message: String, recoverable: Bool) 
    
    func onSessionInvalid(reason: String) 
    
    func onSessionChanged(newSessionId: String) 
    
    func onCustom(kind: String, payloadJson: String) 
    
}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceAgentEventCallback {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // This creates 1-element array, since this seems to be the only way to construct a const
    // pointer that we can pass to the Rust code.
    static let vtable: [UniffiVTableCallbackInterfaceAgentEventCallback] = [UniffiVTableCallbackInterfaceAgentEventCallback(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterCallbackInterfaceAgentEventCallback.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface AgentEventCallback: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterCallbackInterfaceAgentEventCallback.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface AgentEventCallback: handle missing in uniffiClone")
            }
        },
        onText: { (
            uniffiHandle: UInt64,
            text: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceAgentEventCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onText(
                     text: try FfiConverterString.lift(text)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onToolStart: { (
            uniffiHandle: UInt64,
            id: RustBuffer,
            name: RustBuffer,
            inputJson: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceAgentEventCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onToolStart(
                     id: try FfiConverterString.lift(id),
                     name: try FfiConverterString.lift(name),
                     inputJson: try FfiConverterString.lift(inputJson)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onToolProgress: { (
            uniffiHandle: UInt64,
            id: RustBuffer,
            updateJson: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceAgentEventCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onToolProgress(
                     id: try FfiConverterString.lift(id),
                     updateJson: try FfiConverterString.lift(updateJson)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onToolEnd: { (
            uniffiHandle: UInt64,
            id: RustBuffer,
            name: RustBuffer,
            outputJson: RustBuffer,
            success: Int8,
            durationMs: UInt64,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceAgentEventCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onToolEnd(
                     id: try FfiConverterString.lift(id),
                     name: try FfiConverterString.lift(name),
                     outputJson: try FfiConverterString.lift(outputJson),
                     success: try FfiConverterBool.lift(success),
                     durationMs: try FfiConverterUInt64.lift(durationMs)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onResult: { (
            uniffiHandle: UInt64,
            text: RustBuffer,
            usage: RustBuffer,
            metadataJson: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceAgentEventCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onResult(
                     text: try FfiConverterString.lift(text),
                     usage: try FfiConverterOptionTypeFfiUsage.lift(usage),
                     metadataJson: try FfiConverterString.lift(metadataJson)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onError: { (
            uniffiHandle: UInt64,
            code: RustBuffer,
            message: RustBuffer,
            recoverable: Int8,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceAgentEventCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onError(
                     code: try FfiConverterTypeFfiErrorCode_lift(code),
                     message: try FfiConverterString.lift(message),
                     recoverable: try FfiConverterBool.lift(recoverable)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onSessionInvalid: { (
            uniffiHandle: UInt64,
            reason: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceAgentEventCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onSessionInvalid(
                     reason: try FfiConverterString.lift(reason)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onSessionChanged: { (
            uniffiHandle: UInt64,
            newSessionId: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceAgentEventCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onSessionChanged(
                     newSessionId: try FfiConverterString.lift(newSessionId)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onCustom: { (
            uniffiHandle: UInt64,
            kind: RustBuffer,
            payloadJson: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceAgentEventCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onCustom(
                     kind: try FfiConverterString.lift(kind),
                     payloadJson: try FfiConverterString.lift(payloadJson)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )]
}

private func uniffiCallbackInitAgentEventCallback() {
    uniffi_gorp_ffi_fn_init_callback_vtable_agenteventcallback(UniffiCallbackInterfaceAgentEventCallback.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceAgentEventCallback {
    fileprivate static let handleMap = UniffiHandleMap<AgentEventCallback>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceAgentEventCallback : FfiConverter {
    typealias SwiftType = AgentEventCallback
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceAgentEventCallback_lift(_ handle: UInt64) throws -> AgentEventCallback {
    return try FfiConverterCallbackInterfaceAgentEventCallback.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceAgentEventCallback_lower(_ v: AgentEventCallback) -> UInt64 {
    return FfiConverterCallbackInterfaceAgentEventCallback.lower(v)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionDouble: FfiConverterRustBuffer {
    typealias SwiftType = Double?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterDouble.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterDouble.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeFfiChannel: FfiConverterRustBuffer {
    typealias SwiftType = FfiChannel?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeFfiChannel.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeFfiChannel.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeFfiScheduledPrompt: FfiConverterRustBuffer {
    typealias SwiftType = FfiScheduledPrompt?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeFfiScheduledPrompt.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeFfiScheduledPrompt.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeFfiUsage: FfiConverterRustBuffer {
    typealias SwiftType = FfiUsage?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeFfiUsage.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeFfiUsage.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiChannel: FfiConverterRustBuffer {
    typealias SwiftType = [FfiChannel]

    public static func write(_ value: [FfiChannel], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiChannel.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiChannel] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiChannel]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiChannel.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiScheduledPrompt: FfiConverterRustBuffer {
    typealias SwiftType = [FfiScheduledPrompt]

    public static func write(_ value: [FfiScheduledPrompt], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiScheduledPrompt.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiScheduledPrompt] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiScheduledPrompt]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiScheduledPrompt.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_gorp_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_gorp_ffi_checksum_method_ffiagenthandle_abandon_session() != 52334) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_gorp_ffi_checksum_method_ffiagenthandle_cancel() != 46635) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_gorp_ffi_checksum_method_ffiagenthandle_load_session() != 44622) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_gorp_ffi_checksum_method_ffiagenthandle_name() != 34622) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_gorp_ffi_checksum_method_ffiagenthandle_new_session() != 61061) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_gorp_ffi_checksum_method_ffiagenthandle_prompt() != 53644) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_gorp_ffi_checksum_method_ffiagentregistry_available_backends() != 9433) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_gorp_ffi_checksum_method_ffiagentregistry_create() != 57110) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_gorp_ffi_checksum_method_ffischedulerstore_cancel_schedule() != 25195) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_gorp_ffi_checksum_method_ffischedulerstore_create_schedule() != 13656) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_gorp_ffi_checksum_method_ffischedulerstore_delete_schedule() != 16298) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_gorp_ffi_checksum_method_ffischedulerstore_get_by_id() != 53824) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_gorp_ffi_checksum_method_ffischedulerstore_list_all() != 10644) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_gorp_ffi_checksum_method_ffischedulerstore_list_by_channel() != 61295) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_gorp_ffi_checksum_method_ffischedulerstore_list_by_room() != 28488) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_gorp_ffi_checksum_method_ffischedulerstore_pause_schedule() != 13971) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_gorp_ffi_checksum_method_ffischedulerstore_resume_schedule() != 27812) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_gorp_ffi_checksum_method_ffisessionstore_create_channel() != 145) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_gorp_ffi_checksum_method_ffisessionstore_delete_by_room() != 2298) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_gorp_ffi_checksum_method_ffisessionstore_delete_channel() != 37340) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_gorp_ffi_checksum_method_ffisessionstore_get_by_name() != 23564) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_gorp_ffi_checksum_method_ffisessionstore_get_by_room() != 15203) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_gorp_ffi_checksum_method_ffisessionstore_get_by_session_id() != 38514) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_gorp_ffi_checksum_method_ffisessionstore_get_setting() != 50858) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_gorp_ffi_checksum_method_ffisessionstore_list_all() != 33933) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_gorp_ffi_checksum_method_ffisessionstore_mark_started() != 38948) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_gorp_ffi_checksum_method_ffisessionstore_reset_session() != 28184) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_gorp_ffi_checksum_method_ffisessionstore_set_setting() != 26312) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_gorp_ffi_checksum_method_ffisessionstore_update_backend_type() != 41290) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_gorp_ffi_checksum_constructor_ffiagentregistry_new() != 12494) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_gorp_ffi_checksum_constructor_ffischedulerstore_new() != 61189) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_gorp_ffi_checksum_constructor_ffisessionstore_new() != 14231) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_gorp_ffi_checksum_method_agenteventcallback_on_text() != 9303) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_gorp_ffi_checksum_method_agenteventcallback_on_tool_start() != 46582) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_gorp_ffi_checksum_method_agenteventcallback_on_tool_progress() != 43414) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_gorp_ffi_checksum_method_agenteventcallback_on_tool_end() != 8915) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_gorp_ffi_checksum_method_agenteventcallback_on_result() != 56656) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_gorp_ffi_checksum_method_agenteventcallback_on_error() != 45705) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_gorp_ffi_checksum_method_agenteventcallback_on_session_invalid() != 48632) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_gorp_ffi_checksum_method_agenteventcallback_on_session_changed() != 7121) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_gorp_ffi_checksum_method_agenteventcallback_on_custom() != 57611) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitAgentEventCallback()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureGorpFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all