// ABOUTME: Prometheus metrics definitions and initialization
// ABOUTME: Exposes counters, gauges, and histograms for monitoring gorp

use anyhow::{Context, Result};
use metrics::{counter, gauge, histogram, describe_counter, describe_gauge, describe_histogram};
use metrics_exporter_prometheus::{PrometheusBuilder, PrometheusHandle};

/// Initialize the Prometheus metrics recorder and return the handle for the /metrics endpoint
pub fn init_metrics() -> Result<PrometheusHandle> {
    let builder = PrometheusBuilder::new();
    let handle = builder
        .install_recorder()
        .context("Failed to install Prometheus recorder")?;

    // Describe all metrics for documentation
    describe_counters();
    describe_gauges();
    describe_histograms();

    Ok(handle)
}

fn describe_counters() {
    describe_counter!(
        "gorp_messages_received_total",
        "Total number of messages received from Matrix"
    );
    describe_counter!(
        "gorp_messages_sent_total",
        "Total number of messages sent to Matrix"
    );
    describe_counter!(
        "gorp_claude_invocations_total",
        "Total number of Claude CLI invocations"
    );
    describe_counter!(
        "gorp_webhook_requests_total",
        "Total number of webhook requests received"
    );
    describe_counter!(
        "gorp_tools_used_total",
        "Total number of tools used by Claude"
    );
    describe_counter!(
        "gorp_errors_total",
        "Total number of errors encountered"
    );
    describe_counter!(
        "gorp_commands_total",
        "Total number of bot commands processed"
    );
    describe_counter!(
        "gorp_rooms_created_total",
        "Total number of Matrix rooms created"
    );
    describe_counter!(
        "gorp_schedules_executed_total",
        "Total number of scheduled prompts executed"
    );
    describe_counter!(
        "gorp_claude_input_tokens_total",
        "Total input tokens used by Claude"
    );
    describe_counter!(
        "gorp_claude_output_tokens_total",
        "Total output tokens generated by Claude"
    );
    describe_counter!(
        "gorp_claude_cache_read_tokens_total",
        "Total cache read tokens by Claude"
    );
    describe_counter!(
        "gorp_claude_cache_creation_tokens_total",
        "Total cache creation tokens by Claude"
    );
    describe_counter!(
        "gorp_claude_cost_cents_total",
        "Total cost in cents (USD) for Claude API usage"
    );
}

fn describe_gauges() {
    describe_gauge!(
        "gorp_channels_active",
        "Current number of active channels"
    );
    describe_gauge!(
        "gorp_schedules_active",
        "Current number of active schedules"
    );
}

fn describe_histograms() {
    describe_histogram!(
        "gorp_claude_response_duration_seconds",
        "Duration of Claude CLI invocations in seconds"
    );
    describe_histogram!(
        "gorp_claude_response_length_bytes",
        "Length of Claude responses in bytes"
    );
    describe_histogram!(
        "gorp_message_processing_duration_seconds",
        "Total duration of message processing in seconds"
    );
    describe_histogram!(
        "gorp_webhook_request_duration_seconds",
        "Duration of webhook request processing in seconds"
    );
}

// ============================================================================
// Helper functions for recording metrics
// ============================================================================

/// Record a message received from Matrix
pub fn record_message_received(message_type: &str) {
    counter!("gorp_messages_received_total", "type" => message_type.to_string()).increment(1);
}

/// Record a message sent to Matrix
pub fn record_message_sent() {
    counter!("gorp_messages_sent_total").increment(1);
}

/// Record a Claude CLI invocation
pub fn record_claude_invocation(source: &str) {
    counter!("gorp_claude_invocations_total", "source" => source.to_string()).increment(1);
}

/// Record a webhook request
pub fn record_webhook_request(status: &str) {
    counter!("gorp_webhook_requests_total", "status" => status.to_string()).increment(1);
}

/// Record a tool usage by Claude
pub fn record_tool_used(tool_name: &str) {
    counter!("gorp_tools_used_total", "tool" => tool_name.to_string()).increment(1);
}

/// Record an error
pub fn record_error(error_type: &str) {
    counter!("gorp_errors_total", "type" => error_type.to_string()).increment(1);
}

/// Record a bot command
pub fn record_command(command: &str) {
    counter!("gorp_commands_total", "command" => command.to_string()).increment(1);
}

/// Record a room creation
pub fn record_room_created() {
    counter!("gorp_rooms_created_total").increment(1);
}

/// Record a schedule execution
pub fn record_schedule_executed() {
    counter!("gorp_schedules_executed_total").increment(1);
}

/// Update the active channels gauge
pub fn set_active_channels(count: u64) {
    gauge!("gorp_channels_active").set(count as f64);
}

/// Increment the active channels gauge
pub fn increment_active_channels() {
    gauge!("gorp_channels_active").increment(1.0);
}

/// Decrement the active channels gauge
pub fn decrement_active_channels() {
    gauge!("gorp_channels_active").decrement(1.0);
}

/// Update the active schedules gauge
pub fn set_active_schedules(count: u64) {
    gauge!("gorp_schedules_active").set(count as f64);
}

/// Increment the active schedules gauge
pub fn increment_active_schedules() {
    gauge!("gorp_schedules_active").increment(1.0);
}

/// Decrement the active schedules gauge
pub fn decrement_active_schedules() {
    gauge!("gorp_schedules_active").decrement(1.0);
}

/// Record Claude response duration
pub fn record_claude_duration(duration_secs: f64) {
    histogram!("gorp_claude_response_duration_seconds").record(duration_secs);
}

/// Record Claude response length
pub fn record_claude_response_length(length_bytes: usize) {
    histogram!("gorp_claude_response_length_bytes").record(length_bytes as f64);
}

/// Record total message processing duration
pub fn record_message_processing_duration(duration_secs: f64) {
    histogram!("gorp_message_processing_duration_seconds").record(duration_secs);
}

/// Record webhook request duration
pub fn record_webhook_duration(duration_secs: f64) {
    histogram!("gorp_webhook_request_duration_seconds").record(duration_secs);
}

/// Record Claude token usage
pub fn record_claude_tokens(input: u64, output: u64, cache_read: u64, cache_creation: u64) {
    counter!("gorp_claude_input_tokens_total").increment(input);
    counter!("gorp_claude_output_tokens_total").increment(output);
    counter!("gorp_claude_cache_read_tokens_total").increment(cache_read);
    counter!("gorp_claude_cache_creation_tokens_total").increment(cache_creation);
}

/// Record Claude cost in cents (we use cents to avoid floating point counter issues)
pub fn record_claude_cost_cents(cost_cents: u64) {
    counter!("gorp_claude_cost_cents_total").increment(cost_cents);
}
